version: '3.9'

services:
  backend_db:
    container_name: backendProject
    image: postgres:12
    ports:
      - 5440:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:

      - backendProjectData:/var/lib/postgresql/data
volumes:
  backendProjectData: {}